name = "tracking-notifier"
main = "tracking-notifier.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "ORDER_TRACKING"
id = "3a42c00481164aeea0fe0ad9ba73d85f"
